// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5pZG3ifFgm4Z0LgGfpYQ5JPBmn_QU0QI',
    appId: '1:235400726062:android:06c34a835883dz975608d9',
    messagingSenderId: '235400726062',
    projectId: 'flutter-deeplink-demo-project',
    storageBucket: 'flutter-deeplink-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5pZG3ifFgm4Z0LgGfpYQ5JPBmn_QU0QI',
    appId: '1:235400726062:ios:9b703d743fd3c04s7608d9',
    messagingSenderId: '235400726062',
    projectId: 'flutter-deeplink-demo-project',
    storageBucket: 'flutter-deeplink-demo-project.appspot.com',
    iosClientId: '235400726062-f8sabiucf3cvsht73plqvs4flpqprrbf.apps.googleusercontent.com',
    iosBundleId: 'com.sarj33t.flutterDeeplinkDemo',
  );
}
